name: FloppaAC
version: 1.8.4
main: pl.floppaac.FloppaAC
api-version: '1.13'
author: Kl3ban
description: Lightweight server-side anticheat. FakeLag, KillAura, Speed, Fly. Zero dependencies.
commands:
  floppaac:
    description: Manage FloppaAC
    usage: /floppaac <alerts|verbose|vl|clear|status|debug|reload>
    permission: floppaac.staff
    aliases: [flac, fac]
permissions:
  floppaac.staff:
    description: Alerts and VL overview
    default: op
  floppaac.admin:
    description: Punishment management and reload
    default: op
  floppaac.bypass:
    description: Bypass checks
    default: false
